# Generated by Django 5.1.4 on 2025-02-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_qrcode_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
