# Generated by Django 5.1.4 on 2025-03-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_qrcodelimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodelimit',
            old_name='limit_standart',
            new_name='limit_standard',
        ),
    ]
